import './bootstrap';
import { initPageLoader } from './page-loader';
import { initPasswordToggles } from './password-toggle';
import { initSlidePanels } from './slide-panel';
import { initActionMenus } from './action-menu';
import { initTableFilters } from './table-filter';
import { initFlashToast } from './flash-toast';
import { initAccountInvites } from './account-invites';
import { initAccountEdit } from './account-edit';
import { initProfileMenu } from './profile-menu';
import { initSidebar } from './sidebar';
import { initGuideMenu } from './guide-menu';
import { initEleveFiche } from './eleve-fiche';
import { initEleveTuteurDocument } from './eleve-tuteur-document';
import { initParametresDossiers } from './parametres-dossiers';
import { initAcademiqueSettings } from './academique-settings';
import { initAnneeAcademiqueShow } from './annee-academique-show';
import { initTabs } from './tabs';
import { initPanelErrorReopen } from './panel-error-reopen';
import { initLiveSearch } from './live-search';
import { initRequiredFieldStyling } from './form-required';
import { initDropdownSelects } from './dropdown-select';
import { initConfirmModals } from './confirm-modal';
import { initConfirmSubmitForms } from './confirm-submit-form';
import { initEleveClasseAssign } from './eleve-classe-assign';
import { initEleveStatutAssign } from './eleve-statut-assign';
import { initTuteurList } from './tuteur-list';
import { initEleveWizard } from './eleve-wizard';
import { initExamens } from './examens';
import { initDecisionPassage } from './decision-passage';
import { initAnneeEdit } from './annees';
import { initBulletinsGeneration } from './bulletins';
import { initBulletinApercu } from './bulletin-apercu';

document.addEventListener('DOMContentLoaded', () => {
    initPageLoader();
    initPasswordToggles();
    initSlidePanels();
    initActionMenus();
    initTableFilters();
    initFlashToast();
    initAccountInvites();
    initAccountEdit();
    initProfileMenu();
    initSidebar();
    initGuideMenu();
    initEleveFiche();
    initEleveTuteurDocument();
    initParametresDossiers();
    initAcademiqueSettings();
    initAnneeAcademiqueShow();
    initTabs();
    initPanelErrorReopen();
    initLiveSearch();
    initDropdownSelects();
    initRequiredFieldStyling();
    initConfirmModals();
    initConfirmSubmitForms();
    initEleveClasseAssign();
    initEleveStatutAssign();
    initTuteurList();
    initEleveWizard();
    initExamens();
    initDecisionPassage();
    initAnneeEdit();
    initBulletinsGeneration();
    initBulletinApercu();
});
