import './bootstrap';
import { initPasswordToggles } from './password-toggle';
import { initSlidePanels } from './slide-panel';
import { initActionMenus } from './action-menu';
import { initTableFilters } from './table-filter';
import { initFlashToast } from './flash-toast';
import { initAccountInvites } from './account-invites';
import { initAccountEdit } from './account-edit';
import { initProfileMenu } from './profile-menu';
import { initSidebar } from './sidebar';
import { initGuideMenu } from './guide-menu';
import { initEleveEdit } from './eleve-edit';
import { initEleveFiche } from './eleve-fiche';
import { initEleveTuteurDocument } from './eleve-tuteur-document';
import { initParametresDossiers } from './parametres-dossiers';
import { initPanelErrorReopen } from './panel-error-reopen';
import { initLiveSearch } from './live-search';

document.addEventListener('DOMContentLoaded', () => {
    initPasswordToggles();
    initSlidePanels();
    initActionMenus();
    initTableFilters();
    initFlashToast();
    initAccountInvites();
    initAccountEdit();
    initProfileMenu();
    initSidebar();
    initGuideMenu();
    initEleveEdit();
    initEleveFiche();
    initEleveTuteurDocument();
    initParametresDossiers();
    initPanelErrorReopen();
    initLiveSearch();
});
