<?php

namespace App\Http\Requests;

use App\Enums\StatutEleve;
use App\Models\ChampPersonnalise;
use App\Models\Eleve;
use App\Models\Niveau;
use App\Models\TypeDocument;
use App\Support\LimitesEnvoi;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

/**
 * Backs the whole fiche élève wizard (resources/js/eleve-wizard.js): all 4
 * steps (classe désirée, infos perso, parents/tuteurs, documents) travel in
 * one request and are always validated in full — there is no longer a
 * "brouillon" (draft, lenient) submission: nom/prénom/sexe/date de
 * naissance/classe désirée, every champ personnalisé marked obligatoire, and
 * (via withValidator) every type de document marked obligatoire or
 * requis_si_transfert (unless the classe désirée is a niveau de première
 * scolarisation — see Niveau::$premiere_scolarisation) are always required.
 */
class SaveEleveWizardRequest extends FormRequest
{
    public function authorize(): bool
    {
        // Access to this feature is already gated by route middleware.
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        $rules = [
            'niveau_souhaite_id' => ['required', 'exists:niveaux,id'],
            // Not generated by the app: issued by the Educmaster (government)
            // system and typed in by staff whenever they have it on hand.
            'matricule' => ['nullable', 'string', 'max:100', Rule::unique('eleves', 'matricule')->ignore($this->route('eleve'))],
            'nom' => ['required', 'string', 'max:100'],
            'prenom' => ['required', 'string', 'max:100'],
            'sexe' => ['required', Rule::in(['M', 'F'])],
            'date_naissance' => ['required', 'date', 'before:today'],
            // after:date_naissance only when it's given (a brouillon may not have it yet).
            'date_debut_scolarite' => array_values(array_filter([
                'nullable', 'date', 'before_or_equal:today',
                $this->filled('date_naissance') ? 'after:date_naissance' : null,
            ])),
            'champs' => ['array'],

            'tuteurs' => ['array'],
            'tuteurs.*.existing_id' => ['nullable', 'exists:parent_tuteurs,id'],
            'tuteurs.*.nom_prenom' => ['nullable', 'string', 'max:150'],
            'tuteurs.*.lien_parente' => ['nullable', Rule::in(['Père', 'Mère', 'Tuteur légal', 'Autre'])],
            'tuteurs.*.telephone' => ['nullable', 'string', 'max:30'],
            'tuteurs.*.email' => ['nullable', 'email', 'max:150'],

            'documents' => ['array'],
            'documents.*' => ['nullable', 'file', 'max:5120'],
        ];

        foreach (ChampPersonnalise::query()->get() as $champ) {
            $rules["champs.{$champ->id}"] = [$champ->obligatoire ? 'required' : 'nullable', 'string', 'max:255'];
        }

        // « Sauvegarder en brouillon » : seuls nom et prénom restent exigés
        // (pour retrouver la fiche dans la liste) ; tout ce qui est fourni
        // reste vérifié (format, taille, valeurs autorisées).
        if ($this->enregistreEnBrouillon()) {
            foreach (['niveau_souhaite_id', 'sexe', 'date_naissance'] as $champ) {
                $rules[$champ][0] = 'nullable';
            }

            foreach ($rules as $cle => $regles) {
                if (str_starts_with($cle, 'champs.') && $regles[0] === 'required') {
                    $rules[$cle][0] = 'nullable';
                }
            }
        }

        return $rules;
    }

    /**
     * True when the agent clicked « Sauvegarder en brouillon » on a new
     * fiche, or on one that is still a brouillon. An Actif/Archivé fiche
     * can never be turned back into a brouillon by an edit.
     */
    public function enregistreEnBrouillon(): bool
    {
        $eleve = $this->route('eleve');

        return $this->boolean('brouillon')
            && (! $eleve instanceof Eleve || $eleve->statut === StatutEleve::Brouillon);
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        $messages = [
            'niveau_souhaite_id.required' => 'La classe désirée est obligatoire pour terminer la fiche.',
            'nom.required' => 'Le nom est obligatoire.',
            'prenom.required' => 'Le prénom est obligatoire.',
            'sexe.required' => 'Le sexe est obligatoire.',
            'date_naissance.required' => 'La date de naissance est obligatoire.',
            'date_debut_scolarite.before_or_equal' => 'La date de début de scolarité ne peut pas être dans le futur.',
            'date_debut_scolarite.after' => 'La date de début de scolarité doit être postérieure à la date de naissance.',
            'matricule.unique' => 'Ce matricule est déjà attribué à un autre élève.',
        ];

        // Without this, a missing required champ personnalisé falls back to
        // Laravel's generic English default ("The champs.5 field is
        // required.") since this app has no lang/fr validation overrides —
        // naming the champ explicitly makes the error summary usable.
        foreach (ChampPersonnalise::query()->get() as $champ) {
            $messages["champs.{$champ->id}.required"] = "Le champ « {$champ->libelle} » est obligatoire.";
        }

        // Same idea for documents: name the document and the size limit
        // instead of "The documents.3 field must not be greater than 5120 kilobytes."
        $limiteServeur = LimitesEnvoi::enMo(LimitesEnvoi::octetsMaxParFichier());
        foreach (TypeDocument::query()->get() as $type) {
            $messages["documents.{$type->id}.max"] = "Le document « {$type->libelle} » est trop volumineux (5 Mo maximum). Réduisez sa taille (photo moins lourde, PDF compressé) puis réessayez.";
            // Rejected by PHP itself (upload_max_filesize) before Laravel sees it.
            $messages["documents.{$type->id}.uploaded"] = "Le document « {$type->libelle} » n'a pas pu être envoyé : il dépasse la taille autorisée par le serveur ({$limiteServeur} maximum).";
        }

        return $messages;
    }

    /**
     * Three checks: the same duplicate-nom warning as the old Store/Update
     * EleveRequest, a document format cross-check against
     * TypeDocument::$formats_acceptes (same rule StoreDocumentEleveRequest
     * applies to the fiche modal's own document uploads), and the
     * required-documents check, cross-referencing files uploaded in *this*
     * submission with whatever's already on file from an earlier edit.
     */
    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator) {
            $nom = $this->input('nom');
            $prenom = $this->input('prenom');
            $dateNaissance = $this->input('date_naissance');
            $current = $this->route('eleve');

            // Editing an existing fiche is not the same act as creating a new
            // one: if nom/prénom/date de naissance aren't actually changing
            // in *this* save, no new duplicate risk is being introduced, so
            // don't re-block every future edit just because some other
            // unrelated élève happens to already share this fiche's identity.
            $identiteInchangee = $current
                && $current->nom === $nom
                && $current->prenom === $prenom
                && $current->date_naissance?->format('Y-m-d') === $dateNaissance;

            if ($nom && $prenom && $dateNaissance && ! $identiteInchangee) {
                $existant = Eleve::query()
                    ->where('nom', $nom)
                    ->where('prenom', $prenom)
                    ->whereDate('date_naissance', $dateNaissance)
                    ->when($current, fn ($query) => $query->whereKeyNot($current->id))
                    ->first();

                if ($existant) {
                    $matriculeInfo = $existant->matricule ? "matricule {$existant->matricule}" : 'sans matricule renseigné';
                    $validator->errors()->add(
                        'nom',
                        "Un élève portant ce nom, ce prénom et cette date de naissance existe déjà ({$matriculeInfo}). Vérifiez qu'il ne s'agit pas d'un doublon avant de continuer."
                    );
                }
            }

            foreach ($this->file('documents', []) as $typeDocumentId => $fichier) {
                if (! $fichier || ! $fichier->isValid()) {
                    continue;
                }

                $type = TypeDocument::find($typeDocumentId);

                if (! $type || $type->accepteExtension($fichier->getClientOriginalExtension())) {
                    continue;
                }

                $validator->errors()->add(
                    "documents.{$typeDocumentId}",
                    'Format non accepté pour ce type de document. Formats attendus : '.implode(', ', $type->formatsAcceptes()).'.'
                );
            }

            // Un brouillon peut être enregistré sans ses documents obligatoires.
            if ($this->enregistreEnBrouillon()) {
                return;
            }

            $niveauId = $this->input('niveau_souhaite_id');
            $premiereScolarisation = $niveauId
                ? (bool) Niveau::query()->whereKey($niveauId)->value('premiere_scolarisation')
                : false;

            $typesRequis = TypeDocument::query()->get()->filter(
                fn (TypeDocument $type) => $type->obligatoire || ($type->requis_si_transfert && ! $premiereScolarisation)
            );

            foreach ($typesRequis as $type) {
                $fourniMaintenant = $this->file("documents.{$type->id}") !== null;
                $dejaFourni = $current && $current->documents()->where('type_document_id', $type->id)->exists();

                if (! $fourniMaintenant && ! $dejaFourni) {
                    $validator->errors()->add(
                        "documents.{$type->id}",
                        "Le document « {$type->libelle} » est obligatoire pour terminer cette fiche."
                    );
                }
            }
        });
    }
}
