<?php

namespace App\Http\Requests;

use App\Models\ChampPersonnalise;
use App\Models\Eleve;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

class UpdateEleveRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        $rules = [
            // See StoreEleveRequest: not generated by the app, so optional —
            // excludes the élève being edited from the uniqueness check.
            'matricule' => ['nullable', 'string', 'max:100', Rule::unique('eleves', 'matricule')->ignore($this->route('eleve'))],
            'nom' => ['required', 'string', 'max:100'],
            'prenom' => ['required', 'string', 'max:100'],
            'sexe' => ['required', Rule::in(['M', 'F'])],
            'date_naissance' => ['required', 'date', 'before:today'],
            'niveau_souhaite_id' => ['nullable', 'exists:niveaux,id'],
            'champs' => ['array'],
        ];

        foreach (ChampPersonnalise::query()->get() as $champ) {
            $rules["champs.{$champ->id}"] = [$champ->obligatoire ? 'required' : 'nullable', 'string', 'max:255'];
        }

        return $rules;
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'nom.required' => 'Le nom est obligatoire.',
            'prenom.required' => 'Le prénom est obligatoire.',
            'sexe.required' => 'Le sexe est obligatoire.',
            'date_naissance.required' => 'La date de naissance est obligatoire.',
            'matricule.unique' => 'Ce matricule est déjà attribué à un autre élève.',
        ];
    }

    /**
     * Same duplicate warning as StoreEleveRequest, excluding the élève
     * currently being edited (it will always match itself otherwise).
     *
     * Skipped entirely when nom/prénom/date de naissance aren't actually
     * changing in *this* save: editing an existing fiche isn't creating a
     * new one, so an unrelated élève that happens to already share this
     * fiche's identity must not keep blocking every future, unrelated edit.
     */
    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator) {
            $nom = $this->input('nom');
            $prenom = $this->input('prenom');
            $dateNaissance = $this->input('date_naissance');
            $current = $this->route('eleve');

            if (! $nom || ! $prenom || ! $dateNaissance) {
                return;
            }

            $identiteInchangee = $current
                && $current->nom === $nom
                && $current->prenom === $prenom
                && $current->date_naissance?->format('Y-m-d') === $dateNaissance;

            if ($identiteInchangee) {
                return;
            }

            $existant = Eleve::query()
                ->where('nom', $nom)
                ->where('prenom', $prenom)
                ->whereDate('date_naissance', $dateNaissance)
                ->when($current, fn ($query) => $query->whereKeyNot($current->id))
                ->first();

            if ($existant) {
                $matriculeInfo = $existant->matricule ? "matricule {$existant->matricule}" : 'sans matricule renseigné';
                $validator->errors()->add(
                    'nom',
                    "Un élève portant ce nom, ce prénom et cette date de naissance existe déjà ({$matriculeInfo}). Vérifiez qu'il ne s'agit pas d'un doublon avant de continuer."
                );
            }
        });
    }
}
