<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The matricule is not generated by this application: it's issued by
     * the government's Educmaster system and typed in by staff whenever
     * they have it on hand, which may be well after the fiche is created.
     * So it can no longer be required at creation time.
     *
     * The `unique()` constraint from the original migration is left as-is:
     * this `change()` call only touches nullability, not indexes, so it
     * stays in place untouched (NULLs are exempt from uniqueness checks on
     * every driver this app targets).
     */
    public function up(): void
    {
        Schema::table('eleves', function (Blueprint $table) {
            $table->string('matricule')->nullable()->change();
        });
    }

    public function down(): void
    {
        Schema::table('eleves', function (Blueprint $table) {
            $table->string('matricule')->nullable(false)->change();
        });
    }
};
